drop table if exists MovieGenre;
drop table if exists MovieDirector;
drop table if exists MovieActor;
drop table if exists Review;
drop table if exists Movie;
drop table if exists Actor;
drop table if exists Director;
drop table if exists MaxPersonID;
drop table if exists MaxMovieID;
